<!-- div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">

                <form role="form" class="register-form">
                    <h2>Login <small>accedi al tuo account</small></h2>
                    <hr class="colorgraph">

                    <div class="form-group">
                        <input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email" tabindex="4">
                    </div>

                    <div class="form-group">
                        <input type="password" class="form-control input-lg" id="password" placeholder="Password">
                    </div>

                    <div class="row">
                        <div class="col-xs-4 col-sm-3 col-md-3">
                            <span class="button-checkbox">
                                <button type="button" class="btn" data-color="info" tabindex="7">Ricordami</button>
                                <input type="checkbox" name="t_and_c" id="t_and_c" class="hidden" value="1">
                            </span>
                        </div>
                    </div>

                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-xs-12 col-md-6"><input type="submit" value="Accedi" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
                        <div class="col-xs-12 col-md-6">Non hai un accont? <a href="register.html">Registrati!</a></div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div -->

<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <fieldset>
                <h2>Login <small>accedi al tuo account</small></h2>
                <hr class="colorgraph">
                <?php
                    echo $this->loginForm;
                    echo '<p class="text-error">'.$this->errorMessage.'</p>';
                ?>
            </fieldset>
            </div>
        </div>
    </div>
</div>
