<!-- end header -->
<section id="featured" class="bg">
    <!-- start slider -->
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- Slider -->
                <div id="main-slider" class="main-slider flexslider">
                    <div id="sb-search" class="sb-search">
                        <form>
                            <input class="sb-search-input" placeholder="Enter your search term..." type="text" value="" name="search" id="search">
                            <input class="sb-search-submit" type="submit" value="">
                            <span class="sb-icon-search" title="Click to start searching"></span>
                        </form>
                    </div>
                    <ul class="slides">
                        <li>
                            <img src="img/slides/flexslider/2.jpg" alt="" />
                            <div class="flex-caption">
                                <h3>Risparmia</h3>
                                <p>Hai una stampante, non hai una stampante?</p>
                                <a href="#" class="btn btn-theme">Risparmio</a>
                            </div>
                        </li>
                        <li>
                            <img src="img/slides/flexslider/3.jpg" alt="" />
                            <div class="flex-caption">
                                <h3>Utlite</h3>
                                <p>Non sprecare soldi e tempo inventa crea e stampa</p>
                                <a href="#" class="btn btn-theme">Perfetto</a>
                            </div>
                        </li>
                        <li>
                            <img src="img/slides/flexslider/4.png" alt="" />
                            <div class="flex-caption">
                                <h3>Ricerca facile</h3>
                                <p>Puoi cercare una stampante in qualsiasi localita</p>
                                <a href="#" class="btn btn-theme">Efficace</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- end slider -->
            </div>
        </div>
    </div>


</section>
<!-- section class="callaction">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="cta-text">
                    <h2>Registrati e inizi stampare <span>gratis</span> qualsiasi luogo</h2>
                    <p> La registrazione e' gratuita , bastano pochi minuti </p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cta-btn">
                    <a href="#" class="btn btn-theme btn-lg">Registrati<i class="fa fa-angle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section -->

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center">
                    <h2>Tutto <span class="highlight">gratuito</span> niente costi di registrazione!</h2>
                    <p>Lorem ipsum dolor sit amet, ne duis posse mei, ut cum vero nominati. Sed graece aeterno consectetuer te. Cu duo tota deleniti, vis ea fuisset nostrum. Meliore inciderint qui ne. Suas cotidieque vel ut  ei eros perpetua qui. Ponderum lobortis reformidans</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <div class="box">
                            <div class="aligncenter">
                                <div class="icon">
                                    <i class="fa fa-desktop fa-5x"></i>
                                </div>
                                <h4>Fully responsive</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <div class="box">
                            <div class="aligncenter">
                                <div class="icon">
                                    <i class="fa fa-file-code-o fa-5x"></i>
                                </div>
                                <h4>Fully responsive</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <div class="box">
                            <div class="aligncenter">
                                <div class="icon">
                                    <i class="fa fa-paper-plane-o fa-5x"></i>
                                </div>
                                <h4>Fully responsive</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 col-md-3 col-lg-3">
                        <div class="box">
                            <div class="aligncenter">
                                <div class="icon">
                                    <i class="fa fa-cubes fa-5x"></i>
                                </div>
                                <h4>Fully responsive</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



<!-- div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-sm-6 col-lg-6">
                    <h4>About our company</h4>
                    <p><strong>Meliore inciderint qui ne. Suas cotidieque vel ut lobortis reformidans duo</strong></p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae odit iste exercitationem praesentium deleniti nostrum laborum rem id nihil tempora. Adipisci ea commodi unde nam placeat cupiditate quasi a ducimus rem consequuntur ex eligendi minima voluptatem assumenda voluptas quidem sit maiores odio velit voluptate
                    </p>
                    <p>
                        Mel explicari adipiscing consectetuer no, no mel apeirian scripserit repudiandae, ad assum mundi scribentur eam. Graecis offendit phaedrum eu his, eius ferri quidam eos ad, quis delenit vel ei. Alia modus facete te eos, eu tation appellantur per
                    </p>
                </div>
                <div class="col-sm-6 col-lg-6">
                    <h4>Projects</h4>
                    <div class="progress">
                        <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                            40% Complete (success)
                        </div>
                    </div>
                    <div class="progress">
                        <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                            20% Complete
                        </div>
                    </div>
                    <div class="progress">
                        <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                            60% Complete (warning)
                        </div>
                    </div>
                    <div class="progress">
                        <div class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                            80% Complete
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div -->


    <!-- parallax  -->
    <div id="parallax1" class="parallax text-light text-center marginbot50" data-stellar-background-ratio="0.5">
        <div class="container">
            <div class="row appear stats">
                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="align-center color-white txt-shadow">
                        <div class="icon">
                            <i class="fa fa-print fa-5x"></i>
                        </div>
                        <strong id="counter-coffee" class="number">800</strong><br />
                        <span class="text">Stampanti</span>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="align-center color-white txt-shadow">
                        <div class="icon">
                            <i class="fa fa-user fa-5x"></i>
                        </div>
                        <strong id="counter-music" class="number">3450</strong><br />
                        <span class="text">Utenti</span>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="align-center color-white txt-shadow">
                        <div class="icon">
                            <i class="fa fa-paper-plane fa-5x"></i>
                        </div>
                        <strong id="counter-clock" class="number">501</strong><br />
                        <span class="text">Messaggi</span>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3 col-md-3">
                    <div class="align-center color-white txt-shadow">
                        <div class="icon">
                            <i class="fa fa-line-chart fa-5x"></i>
                        </div>
                        <strong id="counter-heart" class="number">378</strong><br />
                        <span class="text">Nuovi utenti</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>