<?php echo $this->doctype('HTML5'); ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="Language" content="it" />
    <meta http-equiv="Content-type" value="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Bootstrap 3 template for corporate business" />

    <title>.:: SosPrinter</title>
    <?php $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'/css/bootstrap.min.css')."\r" ;?>
    <?php $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'/css/cubeportfolio.min.css')."\r" ;?>
    <?php $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'/plugins/flexslider/flexslider.css')."\r" ;?>
    <?php $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'/css/cubeportfolio.min.css')."\r" ;?>
    <?php $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'/css/style.css')."\r" ;?>
    <?php $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'/skins/default.css')."\r" ;?>

    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/jquery.min.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/bootstrap.min.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/jquery.appear.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/jquery.easing.1.3.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/plugins/flexslider/jquery.flexslider-min.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/plugins/flexslider/flexslider.config.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/jquery.cubeportfolio.min.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/classie.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/stellar.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/uisearch.js')."\r"; ?>
    <?php $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl().'/js/custom.js')."\r"; ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript() ?>

</head>
<body>

<div id="wrapper">

    <header>
        <?php  echo $this->render('header.phtml'); ?>

    </header>
    <section id="featured" class="bg">



        <div class="container">
            <?php echo $this->flashMessenger(); ?>
            <div class="row">
                <div class="col-lg-12">
                             <?php  echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </section>

    <?php echo $this->flashMessenger(); ?>
    <?php  echo $this->render('footer.phtml'); ?>
</div>
</body>
</html>
