<!-- div style="width: 10%" xmlns="http://www.w3.org/1999/html">
    <form action='<?php echo $this->url(); ?>/edit' method='post' accept-charset='UTF-8'>
        <fieldset >
            <legend>Registra</legend>
            <label for='name' >Nome</label>
            <input type='text' name='name' id='name' maxlength="50" /><br>

            <label for='email' >Email</label>
            <input type='text' name='email' id='email' maxlength="50" /><br>

            <label for='phone' >Numero</label>
            <input type='text' name='phone' id='username' maxlength="50" /><br>

            <label for='password' >Password</label>
            <input type='password' name='password' id='password' maxlength="50" /><br><br>

            <input type='submit' name='Submit' value='Submit' />
        </fieldset>
    </form>
</div -->
    <div class="container">

        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <form role="form" class="register-form" action='<?php echo $this->url(); ?>/edit' accept-charset='UTF-8'>
                    <h2>Registrati <small>&egrave; gratis</small></h2>
                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="name" id="name" class="form-control input-lg" placeholder="Nome" tabindex="1" maxlength="50">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="text" name="last_name" id="last_name" class="form-control input-lg" placeholder="Cognome" tabindex="2" maxlength="50">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email" tabindex="4" maxlength="50">
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" tabindex="5">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                <input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-lg" placeholder="Conferma Password" tabindex="6">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4 col-sm-3 col-md-3">
					<span class="button-checkbox">
						<button type="button" class="btn" data-color="info" tabindex="7">Accetto</button>
                        <input type="checkbox" name="t_and_c" id="t_and_c" class="hidden" value="1">
					</span>
                        </div>
                        <div class="col-xs-8 col-sm-9 col-md-9">
                            Cliccando <strong class="label label-primary">Registra</strong>, l'utente accetta i <a href="#" data-toggle="modal" data-target="#t_and_c_m">Termini e Condizioni</a> su questo sito, compreso l'uso dei Cookie.
                        </div>
                    </div>

                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-xs-12 col-md-6"><input type="submit" value="Registrati" class="btn btn-theme btn-block btn-lg" tabindex="7"></div>
                        <div class="col-xs-12 col-md-6">Hai gi&agrave; un account? <a href="login.html">Entra</a></div>
                    </div>
                </form>
            </div>
        </div>
    </div>