
<div style="width: 10%">
    <form action='<?php echo $this->url(); ?>/edit/' method='post' accept-charset='UTF-8'>
        <fieldset >
            <legend>Modifica</legend>
            <label for='name' >Nome</label>
            <input type='text' name='name' id='name' maxlength="50" value="<?php echo $this->object_user['name']?>" />

            <label for='email' >Email</label>
            <input type='text' name='email' id='email' maxlength="50" value="<?php echo $this->object_user['email']?>"/>

            <label for='phone' >Numero</label>
            <input type='text' name='phone' id='phone' maxlength="50" value="<?php echo $this->object_user['phone']?>"/>

            <label for='password' >Password</label>
            <input type='password' name='password' id='password' maxlength="50" placeholder="********" value=""/>

            <input type="hidden" name="id" value="<?php echo $this->object_user['id']?>" />

            <input type='submit' name='Submit' value='Submit' />
        </fieldset>
    </form>
</div>
