<!-- a href="/message/sent">Inviate</a> - <a href="/message/">Ricevute</a -->

<div class="col-lg-4">
    <aside class="left-sidebar">
        <div class="widget">
            <h5 class="widgetheading">Posta</h5>
            <ul class="cat">
                <li><i class="fa fa-angle-right"></i><a href="/message/">Ricevuti</a><span> (<?php echo $this->count_r;?>)</span></li>
                <li><i class="fa fa-angle-right"></i><a href="/message/sent">Inviati</a><span> (<?php echo $this->count_i;?>)</span></li>
            </ul>
        </div>
    </aside>
</div>
