<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Marker</title>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        #map {
            height: 100%;
        }
        #floating-panel {
            position: absolute;
            top: 10px;
            left: 25%;
            z-index: 5;
            background-color: #fff;
            padding: 5px;
            border: 1px solid #999;
            text-align: center;
            font-family: 'Roboto','sans-serif';
            line-height: 30px;
            padding-left: 10px;
        }
        #floating-panel {
            margin-left: -52px;
        }
    </style>
</head>
<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script>

    var var_position;


    function initMap() {

    }

    function start(){
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(getCoordinate);
        } else {
            console.log("Error: navigator.geolocation");
        }
    }

    function getCoordinate(position){
        var_position = position;
        var lat = position.coords.latitude;
        var lng = position.coords.longitude;
        console.log(lat);
        console.log(lng);
        $.post('coordinate', { lat: lat, lng: lng }, function (data) {

        });

    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDgbg1JE7OtJVRBF7j6iahXG7arUp-mXws&callback=initMap">
</script>

<div style="width: 10%">
    <form action='/location/coordinate' method='post' accept-charset='UTF-8'>
        <fieldset >
            <legend>Registra un indirizzo</legend>
            <label for='haddress' >lat</label>
            <input type='text' name='lat' id='lat' maxlength="50" value="41.932898699999996" /><br>
            <label for='haddress' >lng</label>
            <input type='text' name='lng' id='lng' maxlength="50" value="12.6333819" /><br>
            <input type='submit' name='Submit' value='Submit' />
        </fieldset>
    </form>
</div>
<a href="#" onclick="start()" >Test</a>
</body>
</html>